### ISSUE TITLE
Deprecated dependency in use

### ISSUE THREAD

**Issue by jkr442** [paaatrick/playball#25]
Warning generated on install:

***
npm install -g playball
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410

changed 69 packages, and audited 70 packages in 10s

2 packages are looking for funding
  run `npm fund` for details

2 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
***

**Comment by paaatrick** [comment]
Hey thanks for raising this issue. I have a new version in development that includes a lot of dependency upgrades and should resolve this.

**Comment by paaatrick** [comment]
3.0.0 has been released. Currently if you install or update with `npm install -g playball` you should not see warnings about deprecated dependencies.
