### ISSUE TITLE
Display challenges that overturn calls

### ISSUE THREAD

**Issue by grgzhng** [paaatrick/playball#6]
Currently, when a hit is challenged and the call is overturned to be out, the ruling is not displayed and there's no change to the scoreboard. Not too sure if all overturned calls are not displayed but the two screenshots below depict an example in the top of the 4th inning of the game today (5/16) between the Reds and the Cubs. 

![image](https://user-images.githubusercontent.com/9838868/57894108-7d589f00-77fa-11e9-86c6-f4ca4f98e199.png)

![image](https://user-images.githubusercontent.com/9838868/57894344-71b9a800-77fb-11e9-9304-ac8d7993e84f.png)

**Comment by paaatrick** [comment]
Thanks for the detailed info. I'll try to look into it.

**Comment by paaatrick** [comment]
A new major version has been released (3.0.0) and I believe this issue has been resolved.
