### ISSUE TITLE
Anything like this for NFL games?

### ISSUE THREAD

**Issue by joeguilmette** [paaatrick/playball#9]
I have no idea what it would take, but it would be amazing to have this available for NFL games as well.

**Comment by zhonskate** [comment]
> I have no idea what it would take, but it would be amazing to have this available for NFL games as well.

It would be amazing!

**Comment by NathanGiesbrecht** [comment]
I've used this before https://github.com/maxalmonte14/nfl-scores Could use some polish, but does the trick.

**Comment by andrewyli** [comment]
I'm thinking about writing something in Rust for this, I'll let you know if it goes well.

**Comment by paaatrick** [comment]
Not that I know of. Feel free to fork this repo if you find a good data source though!
